name: Test

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  jsdom:
    name: JSDOM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: voidzero-dev/setup-vp@v1.17.0
        with:
          node-version: "24"
          cache: true
      - run: vp install
      - run: vp run test:run

  chromium:
    name: Chromium
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: voidzero-dev/setup-vp@v1.17.0
        with:
          node-version: "24"
          cache: true
      - run: vp install
      - run: vp exec --filter rigid-ui -- playwright install --with-deps chromium
      - run: vp run test:chromium
